#!/bin/bash
RCON_CMDLINE="rcon -a 127.0.0.1:${RCON_PORT} -p ${ADMINPASSWORD}"

# command handler for sourcing instance CFGs and running 
# commands on each instance
source /usr/local/bin/arkmanager.command 

start() {
  runCommandOnInstance start $2
}

backup() {
  runCommandOnInstance backup $2
}

rcon() {
  runCommandOnInstance rcon $2 $3
}

status() {
  runCommandOnInstance status $2 $3
}

stop() {
  runCommandOnInstance stop $2 
}

list() {
  for n in $(getAllInstanceNames); do ( echo "@${n}";);done 
}

logs() {
  runCommandOnInstance logs $2 
}

restore() {
  runCommandOnInstance restore $2 $3
}

saveworld() {
  runCommandOnInstance saveworld $2
}

update(){
  runCommandOnInstance update $2  
}

display_help() {
  echo -e "Usage arkmanager [command] --option <argument>\n"
  cat <<-EOE
    arkmanager allows you to manager ark instances.
    Each instance is a config file, for example, @island could be /etc/arkmanager/instances/island.cfg

	  COMMANDS:
    backup @instanceName            Takes a backup of the Maps SavedArks directory and compresses it. Optionally uploads to S3
                                    Example: arkmanager backup @island
    list                            Lists available configured instances
    logs @instanceName              Tails the logs of given instance
                                    Example: arkmanager logs @island
    rcon @instanceName <command>    Runs RCON command against the instance, Example: rcon @island ListPlayers
    restore @instanceName           Restores latest or given backup to the current directory. Optional paramter: <s3://url>
    start @instanceName             Starts a given instance
    saveworld @instanceName         Runs an RCON command to save the given instance world
    status @instanceName            Gets status of given instance
    stop @instanceName              Gracefully stops given instance
EOE
}

case $1 in
start )      
        start $@
        ;;
status )                
        status $@
        ;; 
backup )                
        backup $@
        ;;
list )                
        list
        ;;
logs )                
        logs $@
        ;;
stop )                
        stop $@
        ;;
saveworld )                
        saveworld $@
        ;;
restore )                
        restore $@
        ;;
rcon )                
        rcon $@
        ;;
update )                
        update $@
        ;;
-h | --help )           display_help
                        ;;
* )                     display_help
esac
