#!/bin/bash
RCON_CMDLINE="rcon -a 127.0.0.1:${RCON_PORT} -p ${ADMINPASSWORD}"

# command handler for sourcing instance CFGs and running 
# commands on each instance
source /usr/local/bin/arkmanager.command 

start() {

  instance=$2

  if [ -z "$instance" ]
  then
        echo "must supply instance, e.g @island"
        exit
  fi

  echo "clearing logs ..."
  rm ${ARK_DIR}/ShooterGame/Saved/Logs/*.log
  
  instance="${instance:1}"
  echo "starting ${instance} ..."

  nohup bash /usr/local/bin/arkmanager.start >/dev/null 2>&1 &
  sleep 3
  echo "Server should be up in a few minutes"
}

backup() {
  runCommandOnInstance backup $2
}

rcon() {
  runCommandOnInstance rcon $2 $3
}

status() {
  runCommandOnInstance status $2
}

stop() {
  runCommandOnInstance stop $2 
}

list() {
  for n in $(getAllInstanceNames); do ( echo "@${n}";);done 
}

logs() {
  runCommandOnInstance logs $2 
}

restore() {
  runCommandOnInstance restore $2 $3
}

saveworld() {
  runCommandOnInstance saveworld $2
}

update(){
  runCommandOnInstance update $2  
}

display_help() {
  echo -e "Usage arkmanager [command] --option <argument>\n"
  cat <<-EOE
	  COMMANDS:
    backup @instanceName            Takes a backup of the Maps SavedArks directory and compresses it. Optionally uploads to S3
    list                            Lists available configured instances
    logs @instanceName              Tails the logs of given instance
    rcon @instanceName <command>    Runs RCON command against the instance, Example: rcon @island ListPlayers
    restore @instanceName           Restores latest or given backup to the current directory. Optional paramter: <s3://url>
 	  start @instanceName             Starts a given instance
    saveworld @instanceName         Runs an RCON command to save the given instance world
    status @instanceName            Gets status of given instance
    stop @instanceName              Gracefully stops given instance
EOE
}

case $1 in
start )      
        start $@
        ;;
status )                
        status $@
        ;; 
backup )                
        backup $@
        ;;
list )                
        list
        ;;
logs )                
        logs $@
        ;;
stop )                
        stop $@
        ;;
saveworld )                
        saveworld $@
        ;;
restore )                
        restore $@
        ;;
rcon )                
        rcon $@
        ;;
update )                
        update $@
        ;;
-h | --help )           display_help
                        ;;
* )                     display_help
esac