#!/bin/bash
RCON_CMDLINE="rcon -a 127.0.0.1:${RCON_PORT} -p ${ADMINPASSWORD}"

# command handler for sourcing instance CFGs and running 
# commands on each instance
source /usr/local/bin/arkmanager.command 

start() {

  instance=$2

  if [ -z "$instance" ]
  then
        echo "must supply instance, e.g @island"
        exit
  fi

  echo "clearing logs ..."
  rm ${ARK_DIR}/ShooterGame/Saved/Logs/*.log
  
  instance="${instance:1}"
  echo "starting ${instance} ..."

  nohup bash /usr/local/bin/arkmanager.start >/dev/null 2>&1 &
  sleep 3
  echo "Server should be up in a few minutes"
}

backup() {
  /usr/local/bin/arkmanager.backup $2
}

rcon() {
  runCommandOnInstance rcon $2 $3
}

status() {
  runCommandOnInstance status $2
}

stop() {
  runCommandOnInstance stop $2 
}

logs() {
  runCommandOnInstance logs $2 
}

restore() {
  runCommandOnInstance restore $2 $3
}

saveworld() {
  runCommandOnInstance saveworld $2
}

update(){
  runCommandOnInstance update $2  
}

display_help() {
    echo 'Usage arkmanager [subcommand] --option <argument>'
	  echo 'SUBCOMMANDS:'
    echo 'backup @instanceName'
    echo 'rcon @instanceName <command> , example: rcon @island ListPlayers'
    echo 'restore @instanceName <s3://url>'
 	  echo 'start @instanceName'
    echo 'saveworld @instanceName'
    echo 'status @instanceName'
    echo 'stop @instanceName'
}

case $1 in
start )      
        start $@
        ;;
status )                
        status $@
        ;; 
backup )                
        backup $@
        ;;
logs )                
        logs $@
        ;;
stop )                
        stop $@
        ;;
saveworld )                
        saveworld $@
        ;;
restore )                
        restore $@
        ;;
rcon )                
        rcon $@
        ;;
update )                
        update $@
        ;;
-h | --help )           display_help
                        ;;
* )                     display_help
esac