---
apiVersion: v1
kind: ConfigMap
metadata:
  name: restore-job
  namespace: arkmanager
data:  
  restore.sh: |
    #!/bin/sh
    
    echo "starting restore job"
    arkmanager restore @all
    tree 

    sleep 15m

---
apiVersion: batch/v1
kind: Job
metadata:
  name: restore
  namespace: arkmanager
spec:
  template:
    spec:
      # nodeSelector:
      #   kubernetes.io/hostname: pool-e4pb1255q-ry244
      containers:
      - name: restore
        image: aimvector/ark-asa-server:0.0.33
        command: ['/bin/sh', '-c', '. /restore/restore.sh']
        volumeMounts:
        - name: restore
          mountPath: /restore
          readOnly: false
        - name: backup-secret
          mountPath: /etc/s3cfg/
          readOnly: false
        - name: ark
          mountPath: /ark
          readOnly: false
        - name: ark-instances
          mountPath: /etc/arkmanager/instances
        - name: ark-ini
          mountPath: /etc/arkmanager/ini
      restartPolicy: Never
      volumes:
      - name: backup-secret
        secret:
          secretName: ark-backup
      - name: restore
        configMap:
          name: restore-job
          defaultMode: 075
      - name: ark-instances
        configMap:
          name: ark-instances
          defaultMode: 0755
      - name: ark-ini
        configMap:
          name: ark-ini
          defaultMode: 0755
      - name: ark
        hostPath:
          path: /disk/ark
  backoffLimit: 1