---
apiVersion: v1
kind: ConfigMap
metadata:
  name: restore-job
  namespace: arkmanager
data:  
  restore.sh: |
    #!/bin/sh
    
    cd /conf 
    mkdir -p /etc/arkmanager/
    cp arkmanager.cfg /etc/arkmanager/arkmanager.cfg
    mkdir -p /etc/arkmanager/instances/
    cp island.cfg /etc/arkmanager/instances/island.cfg

    cd /ark 
    echo "starting restore job"
    arkmanager restore @all 

    tree 

    sleep 15m

---
apiVersion: batch/v1
kind: Job
metadata:
  name: restore
  namespace: arkmanager
spec:
  template:
    spec:
      # nodeSelector:
      #   kubernetes.io/hostname: lke77260-163041-6466e8b94006
      containers:
      - name: restore
        image: aimvector/ark-asa-server:0.0.31
        command: ['/bin/sh', '-c', '. /restore/restore.sh']
        volumeMounts:
        - name: restore
          mountPath: /restore
          readOnly: false
        - name: backup-secret
          mountPath: /etc/s3cfg/
          readOnly: false
        - name: ark
          mountPath: /ark
          readOnly: false
        - name: arkmanager
          mountPath: /conf
      restartPolicy: Never
      volumes:
      - name: backup-secret
        secret:
          secretName: ark-backup
      - name: restore
        configMap:
          name: restore-job
          defaultMode: 075
      - name: arkmanager
        configMap:
          name: ark-configuration
          defaultMode: 0755
      - name: ark
        hostPath:
          path: /ark
  backoffLimit: 1