version: "3.4"
volumes: 
  ark:
services:
  ark-asa:
    build:
      dockerfile: dockerfile
    container_name: ark-asa
    image: aimvector/ark-asa-server:0.0.23
    environment:
    - DISABLE_START_MAPS_ON_BOOT=true
    - SERVERPASSWORD=test
    - ADMINPASSWORD=testadmin
    - BACKUP_DIR=/ark/backups
    - ARK_DIR=/ark
    - DISABLE_INSTALL_ON_BOOT=true
    volumes:
    - ark:/ark
    - ./configs/instances:/etc/arkmanager/instances
    - ./configs/ini:/etc/arkmanager/ini
    - .s3cfg:/etc/s3cfg/.s3cfg
    ports:
    - 30778:30778/udp #island
    - 30779:30779/udp #svartalfheim