version: "3.4"
volumes: 
  ark:
services:
  ark-asa:
    build:
      dockerfile: dockerfile
    container_name: ark-asa
    image: aimvector/ark-asa-server:0.0.34
    environment:
    - SERVERPASSWORD=test
    - ADMINPASSWORD=testadmin
    - BACKUP_DIR=/ark/backups
    - ARK_DIR=/ark
    - CLUSTER_ID=9e722058d7c5d88f9df56cce
    # below for development purposes only
    - DISABLE_INSTALL_ON_BOOT=false #disable installing the game on boot
    - DISABLE_START_MAPS_ON_BOOT=false #disable starting the maps on boot
    volumes:
    - ark:/ark
    - ./configs/instances:/etc/arkmanager/instances
    - ./configs/ini:/etc/arkmanager/ini
    - .s3cfg:/etc/s3cfg/.s3cfg
    ports:
    - 20778:20778/udp #island
    - 20779:20779/udp #scorched earth
    - 20780:20780/udp #the center