version: "3.4"
volumes: 
  ark:
services:
  init: 
    container_name: init
    image: alpine:latest
    command: 
    - /bin/sh 
    - -c 
    - |
      mkdir -p /ark/ShooterGame/Saved/Config/WindowsServer/
      cd /configs
      cp GameUserSettings.ini /ark/ShooterGame/Saved/Config/WindowsServer/
      cp Game.ini /ark/ShooterGame/Saved/Config/WindowsServer/
    volumes:
    - F:\ark\.data/:/ark
    - ./configs/:/configs
  ark-asa:
    build:
      dockerfile: dockerfile
    container_name: ark-asa
    image: aimvector/ark-asa-server:0.0.11
    environment:
    - DISABLE_START_MAPS_ON_BOOT=true
    - SESSION_NAME=ThatLocalDevOpsASA
    - SERVERPASSWORD=test
    - ADMINPASSWORD=testadmin
    - SERVER_PORT=30778
    - QUERY_PORT=30015
    - RCON_PORT=27020
    - BACKUP_DIR=/ark/backups
    - ARK_DIR=/ark
    - MAP_NAME=TheIsland_WP
    volumes:
    - F:\ark\.data/:/ark
    - ./configs/instances/:/etc/arkmanager/instances/
    - .s3cfg:/etc/s3cfg/.s3cfg
    ports:
    #map 1 island
    - 30777:30777/udp 
    - 30778:30778/udp
    - 30015:30015/udp
    - 30016:30016/udp
    - 30777:30777/tcp 
    - 30778:30778/tcp