---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ark-ini
  namespace: arkmanager
data:
  GameUserSettings.ini: |+
    [ServerSettings]
    ShowMapPlayerLocation=True
    AllowThirdPersonPlayer=True
    ServerCrosshair=True
    OverrideOfficialDifficulty=5.0
    DifficultyOffset=1.0
    AdminLogging=false
    PerPlatformMaxStructuresMultiplier=10.00000
    MaxPlatformSaddleStructureLimit=100
    ResourcesRespawnPeriodMultiplier=0.5
    TamingSpeedMultiplier=2
    DisableCryopodEnemyCheck=True
    AllowCryoFridgeOnSaddle=True
    DisableCryopodFridgeRequirement=True
  Game.ini: |+
    [/script/shootergame.shootergamemode]
    TamedDinoCharacterFoodDrainMultiplier=0.25
    FuelConsumptionIntervalMultiplier=2
    bDisableStructurePlacementCollision=true
    MatingIntervalMultiplier=0.001
    EggHatchSpeedMultiplier=40
    BabyMatureSpeedMultiplier=9
    BabyImprintAmountMultiplier=5.0
    BabyCuddleIntervalMultiplier=0.3
    bAllowUnlimitedRespecs=true
    ConfigOverrideItemMaxQuantity=(ItemClassString="PrimalItemConsumable_Honey_C",Quantity=(MaxItemQuantity=5, bIgnoreMultiplier=true))
    ConfigOverrideItemMaxQuantity=(ItemClassString="PrimalItemResource_Gasoline_C",Quantity=(MaxItemQuantity=5000, bIgnoreMultiplier=true))
    ConfigOverrideItemMaxQuantity=(ItemClassString="PrimalItemResource_Hide_C",Quantity=(MaxItemQuantity=1000, bIgnoreMultiplier=true))
    ConfigOverrideItemMaxQuantity=(ItemClassString="PrimalItemResource_Fibers_C",Quantity=(MaxItemQuantity=1000, bIgnoreMultiplier=true))
    ConfigOverrideItemMaxQuantity=(ItemClassString="PrimalItemResource_MetalIngot_C",Quantity=(MaxItemQuantity=1000, bIgnoreMultiplier=true))
    ConfigOverrideItemMaxQuantity=(ItemClassString="PrimalItemResource_ChitinPaste_C",Quantity=(MaxItemQuantity=1000, bIgnoreMultiplier=true))
    ConfigOverrideItemMaxQuantity=(ItemClassString="PrimalItemResource_Polymer_C",Quantity=(MaxItemQuantity=1000, bIgnoreMultiplier=true))
    ConfigOverrideItemMaxQuantity=(ItemClassString="PrimalItemResource_Polymer_Organic_C",Quantity=(MaxItemQuantity=50, bIgnoreMultiplier=true))
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ark-instances
  namespace: arkmanager
data:
  island.cfg: |+
    SESSION_NAME=ThatDevOpsASAv2
    MAP_NAME=TheIsland_WP
    SERVER_PORT=30778
    RCON_PORT=27020
    arkoption_AltSaveDirectoryName=TheIsland_WP
    arkoption_ShowFloatingDamageText=True