apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: arkmanager
  namespace: arkmanager
spec:
  serviceName: arkmanager
  replicas: 1
  selector:
    matchLabels:
      app: arkmanager
  template:
    metadata:
      labels:
        app: arkmanager
    spec:
      tolerations:
      - key: "node.kubernetes.io/memory-pressure"
        operator: "Exists"
        effect: "NoSchedule"
      nodeSelector:
        kubernetes.io/hostname: pool-g1ami3jeb-ofiyo
      imagePullSecrets:
      - name: docker-registry
      containers:
      - name: ark
        image: aimvector/ark-asa-server:0.0.26
        imagePullPolicy: Always
        env:
        - name: BACKUP_DIR
          value: "/ark/backups"
        - name: ARK_DIR
          value: "/ark"
        - name: SERVERPASSWORD
          valueFrom:
            secretKeyRef:
              name: ark-secrets
              key: SERVERPASSWORD
        - name: ADMINPASSWORD
          valueFrom:
            secretKeyRef:
              name: ark-secrets
              key: ADMINPASSWORD
        ports:
        - containerPort: 30777
          name: clientudp1
        - containerPort: 30778
          name: clientudp2
        volumeMounts:
        - name: backup-secret
          mountPath: /etc/s3cfg/
          readOnly: false
        - name: ark-instances
          mountPath: /etc/arkmanager/instances
        - name: ark-ini
          mountPath: /etc/arkmanager/ini
        - name: ark
          mountPath: /ark
          readOnly: false
      volumes:
      - name: backup-secret
        secret:
          secretName: ark-backup
      - name: ark-instances
        configMap:
          name: ark-instances
          defaultMode: 0755
      - name: ark-ini
        configMap:
          name: ark-ini
          defaultMode: 0755
      - name: ark
        hostPath:
          path: /ark
---