---
apiVersion: v1
kind: ConfigMap
metadata:
  name: restore-job
  namespace: arkmanager
data:
  saveRootDirectory: "/ark/ShooterGame/Saved/"
  restore.json: |
    [
      { 
        "instance": "@island"
      }
    ]
  restore.sh: |
    #!/bin/sh
    
    apt-get install -y jq

    echo "configuring s3..."
    if test -f "/etc/s3cfg/.s3cfg"; then
      echo "s3cmd configured, continuing..."
    else
      echo "s3cmd is not configured!"
      exit 
    fi

    download(){    
      mkdir -p /tmp/restore/$3/
      s3cmd --force get $2 /tmp/restore/$3.tar.bz2

      tar -xvjf /tmp/restore/$3.tar.bz2 -C /tmp/restore/$3/
      mkdir -p ${1}${3}/
      for f in /tmp/restore/$3/*/*; do
        yes | cp -r "$f" ${1}${3}/
      done
    }

    for backupItem in $(cat /restore/backup.json | jq -c ".[]");
    do
      backup=$(echo $backupItem | jq ".backup"  | sed s/\"//g)
      restore=$(echo $backupItem | jq ".restore"  | sed s/\"//g)
      echo $backup
      echo $restore

      download $saveRootDirectory $backup $restore
    done

    echo "passing ark ownership to steam user"
    chown -R steam:steam /ark

    echo "done"
    sleep 15m

---
apiVersion: batch/v1
kind: Job
metadata:
  name: restore
  namespace: arkmanager
spec:
  template:
    spec:
      nodeSelector:
        kubernetes.io/hostname: lke77260-163041-6466e8b94006
      containers:
      - name: restore
        image: aimvector/ark-asa-server:0.0.19
        command: ['/bin/sh', '-c', '. /restore/restore.sh']
        env:
        - name: saveRootDirectory
          valueFrom:
            configMapKeyRef:
              name: restore-job
              key: saveRootDirectory
        volumeMounts:
        - name: restore
          mountPath: /restore
          readOnly: false
        - name: backup-secret
          mountPath: /etc/s3cfg/
          readOnly: false
        - name: ark
          mountPath: /ark
          readOnly: false
      restartPolicy: Never
      volumes:
      - name: backup-secret
        secret:
          secretName: ark-backup
      - name: restore
        configMap:
          name: restore-job
          defaultMode: 075
      - name: ark
        hostPath:
          path: /ark
  backoffLimit: 1