---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ark-ini
  namespace: arkmanager
data:
  GameUserSettings.ini: |+
    [ServerSettings]
    IgnorePVPMountedWeaponryRestrictions=True
    ShowMapPlayerLocation=True
    AllowThirdPersonPlayer=True
    ServerCrosshair=True
    OverrideOfficialDifficulty=5.0
    DifficultyOffset=1.0
    AdminLogging=false
    PerPlatformMaxStructuresMultiplier=10.00000
    MaxPlatformSaddleStructureLimit=100
    ResourcesRespawnPeriodMultiplier=0.5
    HarvestAmountMultiplier=2
    TamingSpeedMultiplier=2
    DisableCryopodEnemyCheck=True
    AllowCryoFridgeOnSaddle=True
    DisableCryopodFridgeRequirement=True
    MaxPersonalTamedDinos=1000
    [MessageOfTheDay]
    Duration=60
    Message=Please keep the server clean. Pick up traps. Abandoned structures will be destroyed.
  Game.ini: |+
    [/script/shootergame.shootergamemode]
    TamedDinoCharacterFoodDrainMultiplier=0.25
    FuelConsumptionIntervalMultiplier=2
    bDisableStructurePlacementCollision=true
    MatingIntervalMultiplier=0.001
    EggHatchSpeedMultiplier=40
    BabyMatureSpeedMultiplier=9
    BabyImprintAmountMultiplier=5.0
    BabyCuddleIntervalMultiplier=0.3
    bAllowUnlimitedRespecs=true
    ResourceNoReplenishRadiusPlayers=0.3
    ResourceNoReplenishRadiusStructures=0.3
    ConfigOverrideItemMaxQuantity=(ItemClassString="PrimalItemConsumable_Honey_C",Quantity=(MaxItemQuantity=5, bIgnoreMultiplier=true))
    ConfigOverrideItemMaxQuantity=(ItemClassString="PrimalItemResource_Gasoline_C",Quantity=(MaxItemQuantity=5000, bIgnoreMultiplier=true))
    ConfigOverrideItemMaxQuantity=(ItemClassString="PrimalItemResource_Hide_C",Quantity=(MaxItemQuantity=1000, bIgnoreMultiplier=true))
    ConfigOverrideItemMaxQuantity=(ItemClassString="PrimalItemResource_Fibers_C",Quantity=(MaxItemQuantity=1000, bIgnoreMultiplier=true))
    ConfigOverrideItemMaxQuantity=(ItemClassString="PrimalItemResource_MetalIngot_C",Quantity=(MaxItemQuantity=1000, bIgnoreMultiplier=true))
    ConfigOverrideItemMaxQuantity=(ItemClassString="PrimalItemResource_ChitinPaste_C",Quantity=(MaxItemQuantity=1000, bIgnoreMultiplier=true))
    ConfigOverrideItemMaxQuantity=(ItemClassString="PrimalItemResource_Polymer_C",Quantity=(MaxItemQuantity=1000, bIgnoreMultiplier=true))
    ConfigOverrideItemMaxQuantity=(ItemClassString="PrimalItemResource_Polymer_Organic_C",Quantity=(MaxItemQuantity=50, bIgnoreMultiplier=true))
    ConfigOverrideItemMaxQuantity=(ItemClassString="PrimalItemResource_SnailPaste_C",Quantity=(MaxItemQuantity=1000, bIgnoreMultiplier=true))
    ConfigOverrideItemMaxQuantity=(ItemClassString="PrimalItemResource_Obsidian_C",Quantity=(MaxItemQuantity=1000, bIgnoreMultiplier=true))
    bUseCorpseLocator=True
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ark-instances
  namespace: arkmanager
data:
  island.cfg: |+
    SESSION_NAME=ThatDevOpsASAv2
    MAP_NAME=TheIsland_WP
    SERVER_PORT=30778
    RCON_PORT=27020
    arkoption_AltSaveDirectoryName=TheIsland_WP
    arkoption_ShowFloatingDamageText=True
    arkflag_ClusterDirOverride=/ark/clusters
    # transfering 
    arkoption_PreventDownloadSurvivors=False
    arkoption_PreventDownloadItems=False
    arkoption_PreventDownloadDinos=False
    arkoption_PreventUploadSurvivors=False 
    arkoption_PreventUploadItems=False
    arkoption_PreventUploadDinos=False
  se.cfg: |+
    SESSION_NAME=ThatDevOpsScorchedEarth
    MAP_NAME=ScorchedEarth_WP
    SERVER_PORT=30779
    RCON_PORT=27021
    arkoption_AltSaveDirectoryName=ScorchedEarth_WP
    arkoption_ShowFloatingDamageText=True
    arkflag_ClusterDirOverride=/ark/clusters
    # transfering 
    arkoption_PreventDownloadSurvivors=False
    arkoption_PreventDownloadItems=False
    arkoption_PreventDownloadDinos=False
    arkoption_PreventUploadSurvivors=False 
    arkoption_PreventUploadItems=False
    arkoption_PreventUploadDinos=False
  center.cfg: |+
    SESSION_NAME=ThatDevOpsCenter
    MAP_NAME=TheCenter_WP
    SERVER_PORT=30780
    RCON_PORT=27022
    arkoption_AltSaveDirectoryName=TheCenter_WP
    arkoption_ShowFloatingDamageText=True
    arkflag_ClusterDirOverride=/ark/clusters
    # transfering 
    arkoption_PreventDownloadSurvivors=False
    arkoption_PreventDownloadItems=False
    arkoption_PreventDownloadDinos=False
    arkoption_PreventUploadSurvivors=False 
    arkoption_PreventUploadItems=False
    arkoption_PreventUploadDinos=False
  aberration.cfg: |+
    SESSION_NAME=ThatDevOpsAberration
    MAP_NAME=Aberration_WP
    SERVER_PORT=30781
    RCON_PORT=27023
    arkoption_AltSaveDirectoryName=Aberration_WP
    arkoption_ShowFloatingDamageText=True
    arkflag_ClusterDirOverride=/ark/clusters
    # transfering 
    arkoption_PreventDownloadSurvivors=False
    arkoption_PreventDownloadItems=True
    arkoption_PreventDownloadDinos=True
    arkoption_PreventUploadSurvivors=False 
    arkoption_PreventUploadItems=False
    arkoption_PreventUploadDinos=False
  