apiVersion: v1
kind: Service
metadata:
  name: arkmanager
  namespace: arkmanager
spec:
  type: NodePort
  ports:
  - port: 30778
    protocol: UDP
    name: clientudp2
    nodePort: 30778
  - port: 30779
    protocol: UDP
    name: scorchedearth
    nodePort: 30779
  - port: 30780
    protocol: UDP
    name: center
    nodePort: 30780
  - port: 30781
    protocol: UDP
    name: aberration
    nodePort: 30781
  - port: 30782
    protocol: UDP
    name: extinction
    nodePort: 30782
  - port: 30783
    protocol: UDP
    name: ragnarok
    nodePort: 30783
  selector:
    app: arkmanager