apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: arkmanager
  namespace: arkmanager
spec:
  serviceName: arkmanager
  replicas: 1
  selector:
    matchLabels:
      app: arkmanager
  template:
    metadata:
      labels:
        app: arkmanager
    spec:
      tolerations:
      - key: "node.kubernetes.io/memory-pressure"
        operator: "Exists"
        effect: "NoSchedule"
      - key: "node.kubernetes.io/memory-pressure"
        operator: "Exists"
        effect: "NoExecute"
      - key: "node.kubernetes.io/disk-pressure"
        operator: "Exists"
        effect: "NoSchedule"
      - key: "node.kubernetes.io/disk-pressure"
        operator: "Exists"
        effect: "NoExecute"
      nodeSelector:
        kubernetes.io/hostname: aimveck8s
      imagePullSecrets:
      - name: docker-registry
      containers:
      - name: ark
        image: aimvector/ark-asa-server:0.0.39
        imagePullPolicy: Always
        resources:
          requests:
            memory: "25Gi"
        env:
        - name: BACKUP_DIR
          value: "/ark/backups"
        - name: ARK_DIR
          value: "/ark"
        - name: SERVERPASSWORD
          valueFrom:
            secretKeyRef:
              name: ark-secrets
              key: SERVERPASSWORD
        - name: ADMINPASSWORD
          valueFrom:
            secretKeyRef:
              name: ark-secrets
              key: ADMINPASSWORD
        - name: CLUSTER_ID
          valueFrom:
            secretKeyRef:
              name: ark-secrets
              key: CLUSTER_ID
        - name: DISCORD_URL
          valueFrom:
            secretKeyRef:
              name: ark-secrets
              key: DISCORD_URL
        - name: DISABLE_START_MAPS_ON_BOOT
          value: "true"
        ports:
        - containerPort: 30778
          name: clientudp2
        - containerPort: 30779
          name: scorchedearth
        - containerPort: 30780
          name: center
        - containerPort: 30781
          name: aberration
        - containerPort: 30782
          name: extinction
        - containerPort: 30783
          name: ragnarok  
        volumeMounts:
        - name: backup-secret
          mountPath: /etc/s3cfg/
          readOnly: false
        - name: ark-instances
          mountPath: /etc/arkmanager/instances
        - name: ark-ini
          mountPath: /etc/arkmanager/ini
        - name: ark
          mountPath: /ark
          readOnly: false
      volumes:
      - name: backup-secret
        secret:
          secretName: ark-backup
      - name: ark-instances
        configMap:
          name: ark-instances
          defaultMode: 0755
      - name: ark-ini
        configMap:
          name: ark-ini
          defaultMode: 0755
      - name: ark
        hostPath:
          path: /disk/ark
---