---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ark-configuration
  namespace: arkmanager
data:
  update-configs.sh: |
    #!/bin/sh
    cd /conf 
    mkdir -p /ark/ShooterGame/Saved/Config/WindowsServer/
    mkdir -p /etc/arkmanager/instances/
    
    cp GameUserSettings.ini /ark/ShooterGame/Saved/Config/WindowsServer/
    cp Game.ini /ark/ShooterGame/Saved/Config/WindowsServer/
    cp arkmanager.cfg /etc/arkmanager/arkmanager.cfg

    cp island.cfg /etc/arkmanager/instances/island.cfg
    
  GameUserSettings.ini: |+
    [ServerSettings]
    ShowMapPlayerLocation=True
    AllowThirdPersonPlayer=True
    ServerCrosshair=True
    OverrideOfficialDifficulty=5.0
    DifficultyOffset=1.0
    AdminLogging=false
    PerPlatformMaxStructuresMultiplier=10.00000
    MaxPlatformSaddleStructureLimit=100
    ResourcesRespawnPeriodMultiplier=0.5
    TamingSpeedMultiplier=2
    DisableCryopodEnemyCheck=True
    AllowCryoFridgeOnSaddle=True
    DisableCryopodFridgeRequirement=True
  Game.ini: |+
    [/script/shootergame.shootergamemode]
    TamedDinoCharacterFoodDrainMultiplier=0.25
    FuelConsumptionIntervalMultiplier=2
    bDisableStructurePlacementCollision=true
    MatingIntervalMultiplier=0.2
    EggHatchSpeedMultiplier=12
    BabyMatureSpeedMultiplier=9
    BabyImprintAmountMultiplier=5.0
    BabyCuddleIntervalMultiplier=0.3
  arkmanager.cfg: |+
    BACKUP_DIR=/ark/backups
    ARK_DIR=/ark
  island.cfg: |+
    SESSION_NAME=ThatDevOpsASA
    MAP_NAME=TheIsland_WP
    SERVER_PORT=30778
    RCON_PORT=27020
    arkoption_AltSaveDirectoryName=TheIsland_WP
    arkoption_ShowFloatingDamageText=True
---
