---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ark-configuration
  namespace: arkmanager
data:
  update-configs.sh: |
    #!/bin/sh
    cd /conf 
    mkdir -p /ark/ShooterGame/Saved/Config/WindowsServer/
    mkdir -p /etc/arkmanager/instances/
    
    cp GameUserSettings.ini /ark/ShooterGame/Saved/Config/WindowsServer/
    cp Game.ini /ark/ShooterGame/Saved/Config/WindowsServer/
    cp arkmanager.cfg /etc/arkmanager/arkmanager.cfg

    cp island.cfg /etc/arkmanager/instances/island.cfg
    
  GameUserSettings.ini: |+
    [ServerSettings]
    ShowMapPlayerLocation=True
    AllowThirdPersonPlayer=True
    ServerCrosshair=True
    OverrideOfficialDifficulty=5.0
    DifficultyOffset=1.0
    AdminLogging=false
    PerPlatformMaxStructuresMultiplier=10.00000
    MaxPlatformSaddleStructureLimit=100
    ResourcesRespawnPeriodMultiplier=0.5
    TamingSpeedMultiplier=2
  Game.ini: |+
    [/script/shootergame.shootergamemode]
    BabyMatureSpeedMultiplier=3
    TamedDinoCharacterFoodDrainMultiplier=0.25
    FuelConsumptionIntervalMultiplier=2
    bDisableStructurePlacementCollision=true
  arkmanager.cfg: |+
    BACKUP_DIR=/ark/backups
    ARK_DIR=/ark
  island.cfg: |+
    SESSION_NAME=ThatDevOpsASA
    SERVER_PORT=30778
    QUERY_PORT=30015
    RCON_PORT=27020
---
