apiVersion: v1
kind: Service
metadata:
  name: arkmanager
  namespace: arkmanager
spec:
  type: NodePort
  ports:
  - port: 30777
    protocol: UDP
    name: clientudp1
    nodePort: 30777
  - port: 30778
    protocol: UDP
    name: clientudp2
    nodePort: 30778
  selector:
    app: arkmanager