apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: arkmanager
  namespace: arkmanager
spec:
  serviceName: arkmanager
  replicas: 1
  selector:
    matchLabels:
      app: arkmanager
  template:
    metadata:
      labels:
        app: arkmanager
    spec:
      nodeSelector:
        kubernetes.io/hostname: lke77260-163041-6466e8b94006
      initContainers:
      - name: config
        image: busybox
        command: ['/bin/sh', '-c', './conf/update-configs.sh']
        volumeMounts:
        - name: backup-secret
          mountPath: /etc/s3cfg/
          readOnly: false
        - name: conf
          mountPath: /conf
        - name: arkmanager
          mountPath: /etc/arkmanager/
        - name: ark
          mountPath: /ark
          readOnly: false
      imagePullSecrets:
      - name: docker-registry
      containers:
      - name: ark
        image: aimvector/ark-asa-server:0.0.17
        imagePullPolicy: Always
        env:
        - name: BACKUP_DIR
          value: "/ark/backups"
        - name: ARK_DIR
          value: "/ark"
        - name: SERVERPASSWORD
          valueFrom:
            secretKeyRef:
              name: ark-secrets
              key: SERVERPASSWORD
        - name: ADMINPASSWORD
          valueFrom:
            secretKeyRef:
              name: ark-secrets
              key: ADMINPASSWORD
        ports:
        - containerPort: 30777
          name: clientudp1
        - containerPort: 30778
          name: clientudp2
        - containerPort: 30015
          name: queryportudp1
        - containerPort: 30016
          name: queryportudp2
        volumeMounts:
        - name: backup-secret
          mountPath: /etc/s3cfg/
          readOnly: false
        - name: arkmanager
          mountPath: /etc/arkmanager/
        - name: conf
          mountPath: /conf
          readOnly: false
        - name: ark
          mountPath: /ark
          readOnly: false
      volumes:
      - name: backup-secret
        secret:
          secretName: ark-backup
      - name: conf
        configMap:
          name: ark-configuration
          defaultMode: 0755
      - name: arkmanager 
        emptyDir: {}
      - name: ark
        hostPath:
          path: /ark
---